export const TOKEN = 'token'
export const IMAGE_PREFIX = 'data:image/png;base64,'
export const HOST = 'http://localhost:5000/api'
export const AUTHENTICATE = HOST + '/auth/'
export const REGISTER = HOST + '/users/'
export const CREATE_PROFILE = HOST + '/profile/'